package com.learner;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;

import com.learner.delegate.AppMonitoringDelegateActivity;
import com.learner.delegate.AppsMonitoringDelegateImplV19;
import com.learner.delegate.AppsMonitoringDelegateImplV21;

/**
 * Class represents Start-Up Screen that decides the methodology for
 * Tracking the App-Data generated by User during the Application Lifetime.
 * <p>
 * Developer: Rishabh Dutt Sharma
 * Dated: 5/24/2017.
 */
public class LauncherActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Class<? extends AppMonitoringDelegateActivity> intendedDelegateClass
                = Utils.isNewApi() ? AppsMonitoringDelegateImplV21.class : AppsMonitoringDelegateImplV19.class;

        Intent taskMonitoringIntent = new Intent(this, intendedDelegateClass);
        startActivity(taskMonitoringIntent);
        finish();
    }
}
